In [1]:
#importing the packages
import tensorflow as tf
sess= tf.Session()

In [2]:
#Creating a new Graph(not default)
myGraph=tf.Graph()
with myGraph.as_default():
    variable=tf.Variable(30,name='navin')
    initialize=tf.global_variables_initializer()    

In [3]:
#Running computation in session in graph
with tf.Session(graph=myGraph) as sess:
             sess.run(initialize)
             print(sess.run(variable))

30


In [ ]:
#Output graph to tensorboard
import os
merged = tf.summary.merge_all(key='summaries')
if not os.path.exists('tensorboard_logs/'):
    os.makedirs('tensorboard_logs/')

my_writer = tf.summary.FileWriter('/tensorboard_logs/', sess.graph)
def TB(cleanup=False):
    import webbrowser
    webbrowser.open('http://127.0.1.1:6006')
    !tensorboard --logdir="/tensorboard_logs"

    if cleanup:
        !rm -R tensorboard_logs/

TB(1)   #Graph launch on browser

In [1]:
# 2

In [2]:
import tensorflow as tf
x = tf.constant(12,dtype= 'float32')
sess= tf.Session()
print(sess.run(x))

12.0


In [3]:
# 3

In [4]:
import tensorflow as tf
x = tf.constant(12, dtype= 'float32')
with tf.Session() as sess:
    print(sess.run(x))

12.0


In [5]:
#4

In [6]:
import tensorflow as tf
x = tf.constant(12, dtype= 'float32') 
y = tf.Variable(x + 11)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

23.0


In [7]:
#5

In [8]:
import tensorflow as tf
x = tf.constant([14, 23, 40, 30])
y = tf.Variable(x*2 + 100)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

[128 146 180 160]


In [9]:
#6

In [10]:
#Placeholder is a variable that we can feed data to at a later time
import tensorflow as tf
x = tf.placeholder("float", None)
y = x * 10 + 500
with tf.Session() as sess:
    placeX = sess.run(y, feed_dict={x: [0, 5, 15, 25]})
    print(placeX)

[ 500.  550.  650.  750.]


In [11]:
#7

In [12]:
import tensorflow as tf
x = tf.placeholder("float", [None, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [13]:
#8

In [14]:
import tensorflow as tf
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [15]:
#9

In [16]:
import tensorflow as tf
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [17]:
#10

In [20]:
#Creating tensor
import numpy as np
import tensorflow as tf
image=tf.image.decode_jpeg(tf.read_file('tiger_1.jpg'))
sess=tf.InteractiveSession()
print(sess.run(tf.shape(image)))

[448 467   3]


In [21]:
print(sess.run(image[10:15,0:4,1]))

[[59 59 64 61]
 [62 61 61 59]
 [61 63 63 62]
 [64 63 62 59]
 [73 67 67 66]]


In [22]:
#11

In [23]:
#Fixed Tensors
import tensorflow as tf
sess=tf.Session()
A=tf.zeros([2,3])
print(sess.run(A))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [24]:
#Declare another variable
B=tf.ones([4,3])
print(sess.run(B))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [25]:
C=tf.fill([2,3],13)
print(sess.run(C))

[[13 13 13]
 [13 13 13]]


In [26]:
D=tf.diag([4,-3,2])
print(sess.run(D))

[[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  2]]


In [27]:
E=tf.constant([4,2,3,1])
print(sess.run(E))

[4 2 3 1]


In [28]:
#Sequence tensor

In [29]:
G=tf.range(start=6,limit=45,delta=3)
print(sess.run(G))

[ 6  9 12 15 18 21 24 27 30 33 36 39 42]


In [30]:
H=tf.linspace(10.0,92.0,5) #creates sequence of evenly spaced value
print(sess.run(H))

[ 10.   30.5  51.   71.5  92. ]


In [31]:
#Random Tensor

In [32]:
R1=tf.random_uniform([2,3],minval=0,maxval=4)
print(sess.run(R1))

[[ 2.92919874  1.67547607  3.44423199]
 [ 2.88863468  2.89950752  3.49689388]]


In [33]:
R2=tf.random_normal([2,3],mean=5,stddev=4)
print(sess.run(R2))

[[ 4.92087889  7.51223087  9.2412281 ]
 [ 6.65636778  0.94417238  8.15496731]]


In [34]:
R3=tf.random_shuffle(tf.diag([3,-2,4]))
print(sess.run(R3))

[[ 3  0  0]
 [ 0  0  4]
 [ 0 -2  0]]


In [35]:
R4=tf.random_crop(tf.diag([3,-2,4]),[3,2])
print(sess.run(R4))

[[ 0  0]
 [-2  0]
 [ 0  4]]


In [36]:
print(sess.run(tf.diag([3,-2,4])))

[[ 3  0  0]
 [ 0 -2  0]
 [ 0  0  4]]


In [37]:
print(sess.run(tf.zeros([2,4])))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [38]:
print(sess.run(tf.diag([3,1,5,-2])))

[[ 3  0  0  0]
 [ 0  1  0  0]
 [ 0  0  5  0]
 [ 0  0  0 -2]]


In [39]:
print(sess.run(tf.range(start=4, limit=16, delta=2)))

[ 4  6  8 10 12 14]


In [40]:
#12

In [41]:
#Working with matrices

In [42]:
import tensorflow as tf
import numpy as np
sess=tf.Session()
A=tf.random_uniform([3,2])
B=tf.fill([2,4],3.5)
C=tf.random_uniform([3,4])

In [43]:
print(sess.run(A))

[[ 0.03957546  0.1764729 ]
 [ 0.5654453   0.9730289 ]
 [ 0.30421603  0.64464295]]


In [44]:
print(sess.run(B))

[[ 3.5  3.5  3.5  3.5]
 [ 3.5  3.5  3.5  3.5]]


In [45]:
print(sess.run(tf.matmul(A,B)))    # Matrix multiplication

[[ 4.03358698  4.03358698  4.03358698  4.03358698]
 [ 3.41654873  3.41654873  3.41654873  3.41654873]
 [ 5.25726032  5.25726032  5.25726032  5.25726032]]


In [46]:
print(sess.run(tf.matmul(A,B)+C))    #Multiplication and addition

[[ 2.92311883  3.40393353  3.03996706  2.50866842]
 [ 2.01357698  1.96834517  2.21883726  1.69655538]
 [ 4.47762156  4.3755908   4.68511868  4.95583677]]


In [47]:
#Activation function

In [48]:
#working on tanh function
E=tf.nn.tanh([10,2,0.5,-0.5,-1.0,-2,-10.0])
print(sess.run(E))

[ 1.          0.96402758  0.46211717 -0.46211717 -0.76159418 -0.96402758
 -1.        ]


In [49]:
#sigmoid function
J=tf.nn.sigmoid([10,2,0.5,-0.5,-1.0,-2,-10.0])
print(sess.run(J))

[  9.99954581e-01   8.80797029e-01   6.22459352e-01   3.77540678e-01
   2.68941432e-01   1.19202919e-01   4.53978719e-05]


In [50]:
import tensorflow as tf
sess=tf.Session()
print(sess.run(tf.constant([-2,1,-3,13])))
print('\n\n')
A=tf.nn.relu([-2,1,-3,13])
print(sess.run(A))

[-2  1 -3 13]



[ 0  1  0 13]


In [51]:
import tensorflow as tf
sess=tf.Session()
print(sess.run(tf.constant([-2,1,-3,13])))
print('\n\n')
A=tf.nn.relu6([-2,1,-3,13])
print(sess.run(A))

[-2  1 -3 13]



[0 1 0 6]


In [52]:
import tensorflow as tf
sess=tf.Session()
print(sess.run(tf.constant([[-2,1,-3],[10,-16,-5]])))
print('\n')
C=tf.nn.relu([[-2,1,-3],[10,-16,-5]])
print(sess.run(C))

[[ -2   1  -3]
 [ 10 -16  -5]]


[[ 0  1  0]
 [10  0  0]]


In [53]:
#Relu function
Re=tf.nn.relu([-2,1,-3,13])
print(sess.run(Re))

[ 0  1  0 13]


In [54]:
#elu function
H=tf.nn.elu([10,2,1,0.5,0,-0.5,-1.,-2.,-10.])
print(sess.run(H))

[ 10.           2.           1.           0.5          0.          -0.39346933
  -0.63212055  -0.86466473  -0.99995458]


In [55]:
#Relu6 function
Re6=tf.nn.relu6([10,2,1,0.5,0,-0.5,-1.,-2.,-10.])
print(sess.run(Re6))

[ 6.   2.   1.   0.5  0.   0.   0.   0.   0. ]


In [56]:
#softmax function
X=tf.nn.softmax([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(X))

[  9.99494076e-01   3.35292920e-04   7.48139573e-05   4.53769608e-05
   2.75225175e-05   1.66932514e-05   6.14110377e-06   2.06011097e-09]


In [57]:
#softsign function
Y=tf.nn.softsign([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(Y))

[ 0.90909094  0.66666669  0.33333334  0.         -0.33333334 -0.5
 -0.66666669 -0.90909094]


In [58]:
#softplus function
Z=tf.nn.softplus([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(Z))

[  1.00000458e+01   2.12692809e+00   9.74076986e-01   6.93147182e-01
   4.74076986e-01   3.13261628e-01   1.26928046e-01   4.54177061e-05]


In [66]:
#13

In [59]:
import tensorflow as tf
import numpy as np
sess=tf.Session()

In [60]:
#Assuming prediction model
pred=np.asarray([0.2,0.3,0.5,10.0,12.0,13.0,3.5,7.4,3.9,2.3])
#convert ndarray into tensor
x_val=tf.convert_to_tensor(pred)
#Assuming actual values
actual=np.asarray([0.1,0.4,0.6,9.0,11.0,12.0,3.4,7.1,3.8,2.0])

In [61]:
#L2 loss:L1=(pred-actual)^2
l2=tf.square(pred-actual)
l2_out=sess.run(tf.round(l2))
print(l2_out)

[ 0.  0.  0.  1.  1.  1.  0.  0.  0.  0.]


In [62]:
#L2 loss:L1=abs(pred-actual)
l1=tf.abs(pred-actual)
l1_out=sess.run(l1)
print(l1_out)

[ 0.1  0.1  0.1  1.   1.   1.   0.1  0.3  0.1  0.3]


In [63]:
#cross entropy loss
softmax_xentropy_variable=tf.nn.sigmoid_cross_entropy_with_logits(logits=l1_out,labels=l2_out)
print(sess.run(softmax_xentropy_variable))

[ 0.74439666  0.74439666  0.74439666  0.31326169  0.31326169  0.31326169
  0.74439666  0.85435524  0.74439666  0.85435524]


In [64]:
#14

In [65]:
#Optimization

In [66]:
import tensorflow as tf
import numpy as np

In [67]:
x = tf.Variable(3, name='x', dtype=tf.float32)
log_x = tf.log(x)
log_x_squared = tf.square(log_x)

In [68]:
optimizer = tf.train.GradientDescentOptimizer(0.7)
train = optimizer.minimize(log_x_squared)

In [69]:
init =tf.global_variables_initializer()

In [70]:
#Finnaly running computation
with tf.Session() as session:
    session.run(init)
    print("starting at", "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
    for step in range(10):  
      session.run(train)
      print("step", step, "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))    



starting at x: 3.0 log(x)^2: 1.20695
step 0 x: 2.48731 log(x)^2: 0.830292
step 1 x: 1.97444 log(x)^2: 0.462786
step 2 x: 1.49207 log(x)^2: 0.160134
step 3 x: 1.1166 log(x)^2: 0.0121637
step 4 x: 0.97832 log(x)^2: 0.00048043
step 5 x: 1.00969 log(x)^2: 9.29177e-05
step 6 x: 0.99632 log(x)^2: 1.35901e-05
step 7 x: 1.0015 log(x)^2: 2.24809e-06
step 8 x: 0.999405 log(x)^2: 3.54772e-07
step 9 x: 1.00024 log(x)^2: 5.70574e-08


In [71]:
# importing libraries
import numpy as np
import tensorflow as tf

In [72]:
# placeholders declaration
x=tf. placeholder(tf.int32, [5])
y=tf. placeholder(tf.int32, [5])

In [73]:
# Metrices declaration
acc, acc_op=tf.metrics.accuracy(labels=x, predictions=y)

In [74]:
#session initialization
sess=tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

In [75]:
#value assign
val= sess.run([acc,acc_op], feed_dict={x: [1,1,0,1,0], y: [0,1,0,0,1]})

In [76]:
#print Accuracy
val_acc=sess.run(acc)
print(val_acc)

0.4
