In [1]:
import tensorflow as tf
x = tf.constant(12,dtype= 'float32')
sess= tf.Session()
print(sess.run(x))

12.0


In [2]:
import tensorflow as tf
x = tf.constant(12, dtype= 'float32')
with tf.Session() as sess:
    print(sess.run(x))

12.0


In [3]:
import tensorflow as tf
x = tf.constant(12, dtype= 'float32') 
y = tf.Variable(x + 11)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))


23.0


In [4]:
import tensorflow as tf
x = tf.constant([14, 23, 40, 30])
y = tf.Variable(x*2 + 100)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))


[128 146 180 160]


In [5]:
#Placeholder is a variable that we can feed data to at a later time
import tensorflow as tf
x = tf.placeholder("float", None)
y = x * 10 + 500
with tf.Session() as sess:
    placeX = sess.run(y, feed_dict={x: [0, 5, 15, 25]})
    print(placeX)

[ 500.  550.  650.  750.]


In [6]:
import tensorflow as tf
x = tf.placeholder("float", [None, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [7]:
import tensorflow as tf
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [8]:
import tensorflow as tf
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[ 121.   21.    1.  -19.]
 [ 141.   41.   11.    1.]]


In [9]:
# Weight and Bias as Variables as they are to be tuned
W = tf.Variable([2], dtype=tf.float32) 
b = tf.Variable([3], dtype=tf.float32)
# Training dataset that will be fed while training
x = tf.placeholder(tf.float32)
# Linear Model
linear_model = W * x + b


In [ ]:
import tensorflow as tf
from datasets import flowers
slim = tf.contrib.slim
with tf.Graph().as_default():
 dataset = flowers.get_split('train', flowers_data_dir)
 data_provider = slim.dataset_data_provider.DatasetDataProvider(
 dataset, common_queue_capacity=32, common_queue_min=1)
 image, label = data_provider.get(['image', 'label'])

In [ ]:
# In TF Learn
from tensorflow.contrib import learn
estimator = learn.LinearRegressor(feature_columns, model_dir)
estimator.fit(input_fn=input_fn_train)
estimator.evaluate(input_fn=input_fn_eval)
estimator.predict(x=x)
estimator.export(export_dir)